"""Add invite system fields to User model

Revision ID: 03fced087cda
Revises: abfc8293f8e8
Create Date: 2025-07-16 17:10:05.808543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '03fced087cda'
down_revision = 'abfc8293f8e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('USER', 'ADMIN', name='userrole'), server_default='USER', nullable=False))
        batch_op.add_column(sa.Column('status', postgresql.ENUM('INVITED', 'ACTIVE', 'DISABLED', name='userstatus'), server_default='ACTIVE', nullable=False))
        batch_op.add_column(sa.Column('invitation_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('invitation_token_expires', sa.DateTime(timezone=True), nullable=True))
        batch_op.create_unique_constraint(None, ['invitation_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('invitation_token_expires')
        batch_op.drop_column('invitation_token')
        batch_op.drop_column('status')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
