"""Initial migration

Revision ID: 79dfebf4656a
Revises: fix_size_unit_001
Create Date: 2025-10-06 17:00:26.747061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79dfebf4656a'
down_revision = 'fix_size_unit_001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sold_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('rented_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('leased_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extracted_property', schema=None) as batch_op:
        batch_op.drop_column('leased_date')
        batch_op.drop_column('rented_date')
        batch_op.drop_column('sold_date')

    # ### end Alembic commands ###
